version: "3.8"

services:
  judge:
    build:
      context: ./judge
      dockerfile: Dockerfile
    command: ["./judge", "serve", "--listen", "8080"]
    ports:
      - "8080:8080"
    environment:
      INTERNAL_API_KEY: value
    depends_on:
      db:
        condition: service_healthy
      serve:
        condition: service_started

  serve:
    build:
      context: ./serve
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      PORT: "5000"
      INTERNAL_API_KEY: asd
      DB_URL: "postgres://postgres:example@db:5432/app?sslmode=disable"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
